// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ0C2Q9NVjd_xZGGpJhcW-e0axTkBxl5Y',
    appId: '1:84308035473:web:6b7ee168920be1ed3f3c30',
    messagingSenderId: '84308035473',
    projectId: 'note-app-e56a9',
    authDomain: 'note-app-e56a9.firebaseapp.com',
    storageBucket: 'note-app-e56a9.firebasestorage.app',
    measurementId: 'G-B7W8WVEP1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNVPmGvpaw9tyiFMqL2CVMmIEEmJIVDzE',
    appId: '1:84308035473:android:d68ce6bce03a27313f3c30',
    messagingSenderId: '84308035473',
    projectId: 'note-app-e56a9',
    storageBucket: 'note-app-e56a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1gPBlHIhUl28nn3qAMTFHDS2h1gMoqt8',
    appId: '1:84308035473:ios:d7606836e42092133f3c30',
    messagingSenderId: '84308035473',
    projectId: 'note-app-e56a9',
    storageBucket: 'note-app-e56a9.firebasestorage.app',
    iosBundleId: 'com.example.notesApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1gPBlHIhUl28nn3qAMTFHDS2h1gMoqt8',
    appId: '1:84308035473:ios:d7606836e42092133f3c30',
    messagingSenderId: '84308035473',
    projectId: 'note-app-e56a9',
    storageBucket: 'note-app-e56a9.firebasestorage.app',
    iosBundleId: 'com.example.notesApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ0C2Q9NVjd_xZGGpJhcW-e0axTkBxl5Y',
    appId: '1:84308035473:web:e195418c557e43d53f3c30',
    messagingSenderId: '84308035473',
    projectId: 'note-app-e56a9',
    authDomain: 'note-app-e56a9.firebaseapp.com',
    storageBucket: 'note-app-e56a9.firebasestorage.app',
    measurementId: 'G-2LLPHXF0CK',
  );
}
